In [2]:
import pandas as pd
import scipy.stats as stats
import numpy as np

In [3]:
df = pd.read_excel(r"C:\Users\ACER\Desktop\Data Analitika\ANOVA test.xlsx")
df

    Tələbə_No  Metod_A  Metod_B  Metod_C
0           1       55       72       88
1           2       62       80       92
2           3       70       78       85
3           4       68       85       90
4           5       59       76       81
5           6       75       70       95
6           7       60       82       87
7           8       64       74       89
8           9       71       88       94
9          10       66       79       86
10         11       58       75       82
11         12       63       81       91
12         13       67       77       84
13         14       61       83       93
14         15       69       71       80

In [7]:


print("--- ADDIM 1: NORMALLIQ (SHAPIRO) ---")
# P > 0.05 olmalıdır
print(f"Eyani P-dəyəri: {stats.shapiro(df['Metod_A']).pvalue:.4f}")
print(f"Online P-dəyəri: {stats.shapiro(df['Metod_B']).pvalue:.4f}")
print(f"Hibrid P-dəyəri: {stats.shapiro(df['Metod_C']).pvalue:.4f}")

--- ADDIM 1: NORMALLIQ (SHAPIRO) ---
Eyani P-dəyəri: 0.9973
Online P-dəyəri: 0.9836
Hibrid P-dəyəri: 0.7633

In [9]:
print("\n--- ADDIM 2: HOMOGENLİK (LEVENE) ---")
# P > 0.05 olmalıdır (Varyanslar bərabərdirmi?)
stat, p_levene = stats.levene(df['Metod_A'], df['Metod_B'], df['Metod_C'])
print(f"Levene P-dəyəri: {p_levene:.4f}")

--- ADDIM 2: HOMOGENLİK (LEVENE) ---
Levene P-dəyəri: 0.8417

In [11]:
print("\n--- ADDIM 3: ANOVA TESTİ ---")
# P < 0.05 olmalıdır (Fərq varmı?)
f_stat, p_anova = stats.f_oneway(df['Metod_A'], df['Metod_B'], df['Metod_C'])
print(f"ANOVA P-dəyəri: {p_anova:.4f}") 

if p_anova < 0.05:
    print("\nNƏTİCƏ: Fərq var! (H0 rədd edilir)")
else:
    print("netice ferqi yoxdur")

--- ADDIM 3: ANOVA TESTİ ---
ANOVA P-dəyəri: 0.0000

NƏTİCƏ: Fərq var! (H0 rədd edilir)

In [13]:

# Datanı Tukey testinin başa düşəcəyi formata salırıq (Melt edirik)
df_melt = pd.melt(df, value_vars=['Metod_A', 'Metod_B', 'Metod_C'], 
                  var_name='Metodlar', value_name='Qiymetler')

# Əgər datanızda boş (NaN) dəyərlər varsa, xəta verməməsi üçün onları silirik
df_melt = df_melt.dropna()
df_melt

   Metodlar  Qiymetler
0   Metod_A         55
1   Metod_A         62
2   Metod_A         70
3   Metod_A         68
4   Metod_A         59
5   Metod_A         75
6   Metod_A         60
7   Metod_A         64
8   Metod_A         71
9   Metod_A         66
10  Metod_A         58
11  Metod_A         63
12  Metod_A         67
13  Metod_A         61
14  Metod_A         69
15  Metod_B         72
16  Metod_B         80
17  Metod_B         78
18  Metod_B         85
19  Metod_B         76
20  Metod_B         70
21  Metod_B         82
22  Metod_B         74
23  Metod_B         88
24  Metod_B         79
25  Metod_B         75
26  Metod_B         81
27  Metod_B         77
28  Metod_B         83
29  Metod_B         71
30  Metod_C         88
31  Metod_C         92
32  Metod_C         85
33  Metod_C         90
34  Metod_C         81
35  Metod_C         95
36  Metod_C         87
37  Metod_C         89
38  Metod_C         94
39  Metod_C         86
40  Metod_C         82
41  Metod_C         91
42  Metod_C         84
43  Metod_C         93
44  Metod_C         80

In [14]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Tukey HSD testini tətbiq edirik
tukey_netice = pairwise_tukeyhsd(endog=df_melt['Qiymetler'], 
                                 groups=df_melt['Metodlar'], 
                                 alpha=0.05)

# Nəticə cədvəlini ekrana yazdırırıq
print("\n--- ADDIM 4: TUKEY HSD TESTİ ---")
print(tukey_netice)

--- ADDIM 4: TUKEY HSD TESTİ ---
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
 group1  group2 meandiff p-adj  lower   upper  reject
-----------------------------------------------------
Metod_A Metod_B  13.5333   0.0  8.9337 18.1329   True
Metod_A Metod_C  23.2667   0.0 18.6671 27.8663   True
Metod_B Metod_C   9.7333   0.0  5.1337 14.3329   True
-----------------------------------------------------