In [2]:
# Pandas 
# "Pandas – Excel-in 'steroidli' və proqramlaşdırıla bilən versiyasıdır."

# DataFrame

import pandas as pd

In [3]:
liste = [1,2,3,4,5,6,7,8,9]
df = pd.DataFrame(data=liste)
df

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9

In [4]:
melumat = [["vahid",700],
["akif",800],["aysel",900]]

df2 = pd.DataFrame(data=melumat)
df2

       0    1
0  vahid  700
1   akif  800
2  aysel  900

In [5]:
melumat = [["vahid",700],
["akif",800],["aysel",900]]

df2 = pd.DataFrame(data=melumat,columns=("ad","maaş"))
df2

      ad  maaş
0  vahid   700
1   akif   800
2  aysel   900

In [7]:
melumat = [["vahid",700],
["akif",800],["aysel",900]]

df2 = pd.DataFrame(data=melumat,columns=("ad","maaş"),index=(1,2,3))
df2

      ad  maaş
1  vahid   700
2   akif   800
3  aysel   900

In [8]:

# Məlumatın hazırlanması (Dictionary formatında)
telebeler = {
    "Ad": ["Aygün", "Elvin", "Nigar"],
    "Yaş": [21, 22, 20],
    "Fakultə": ["Riyaziyyat", "İqtisadiyyat", "Fizika"]
}

# DataFrame-in yaradılması
df = pd.DataFrame(data=telebeler)

print(df)

      Ad  Yaş       Fakultə
0  Aygün   21    Riyaziyyat
1  Elvin   22  İqtisadiyyat
2  Nigar   20        Fizika

In [10]:
# sütuna ad vermə  - columns

melumat = [["vahid",700],
["akif",800],["aysel",900]]

df2 = pd.DataFrame(data=melumat)
df2.columns = ("ad","maas")
df2

      ad  maas
0  vahid   700
1   akif   800
2  aysel   900

In [16]:
# sütuna ad vermə  - .rename
melumat = [["vahid",700],
["akif",800],["aysel",900]]

df2 = pd.DataFrame(data=melumat,columns=("ad","maaş"),index=(1,2,3))
print(df2,end="\n\n")

df2 = df2.rename(columns = {"ad":"işçinin adı"})
print(df2)

      ad  maaş
1  vahid   700
2   akif   800
3  aysel   900

  işçinin adı  maaş
1       vahid   700
2        akif   800
3       aysel   900

In [17]:
# İndeks Təyin Etmə (set_index) 

data = {
    'ID': [101, 102, 103],
    'Ad': ['Ali', 'Vəli', 'Həsən'],
    'Maas': [1000, 1200, 1500]
}
df = pd.DataFrame(data)

# 'ID' sütununu indeks edirik (Artıq 0, 1, 2 olmayacaq)
df = df.set_index('ID')

# Nəticədə ID sütunu artıq datanın içində yox, sol tərəfdə qalın şriftlə görünəcək.
print(df)

        Ad  Maas
ID
101    Ali  1000
102   Vəli  1200
103  Həsən  1500

In [19]:
# İndeks Təyin Etmə (set_index) 

data = {
    'ID': [101, 102, 103],
    'Ad': ['Ali', 'Vəli', 'Həsən'],
    'Maas': [1000, 1200, 1500]
}
df = pd.DataFrame(data)

# 'ID' sütununu indeks edirik (Artıq 0, 1, 2 olmayacaq)
df = df.set_index('ID')

# Nəticədə ID sütunu artıq datanın içində yox, sol tərəfdə qalın şriftlə görünəcək.
print(df,end="\n\n")

df = df.reset_index()
print(df)

        Ad  Maas
ID
101    Ali  1000
102   Vəli  1200
103  Həsən  1500

    ID     Ad  Maas
0  101    Ali  1000
1  102   Vəli  1200
2  103  Həsən  1500

In [20]:
# df.loc[sətir_adı, sütun_adı] 

data = {
    'Ad': ['Aygün', 'Elvin', 'Nigar', 'Samir'],
    'Yas': [21, 22, 20, 25],
    'Bal': [85, 90, 78, 92]
}

# İndeksi xüsusi olaraq ID kodları edirik
df = pd.DataFrame(data, index=['ID_101', 'ID_102', 'ID_103', 'ID_104'])

print(df)

           Ad  Yas  Bal
ID_101  Aygün   21   85
ID_102  Elvin   22   90
ID_103  Nigar   20   78
ID_104  Samir   25   92

In [21]:
# Sətir adı: 'ID_102', Sütun adı: 'Bal'
deyer = df.loc['ID_102', 'Bal']
print(deyer) 
# Nəticə: 90

90

In [23]:
# Siyahı (List) içində siyahı veririk
secim = df.loc[['ID_101', 'ID_103'], ['Ad', 'Yas']]
secim

           Ad  Yas
ID_101  Aygün   21
ID_103  Nigar   20

In [25]:
# Diqqət: ID_103 də nəticədə olacaq!
araliq = df.loc['ID_101':'ID_103', 'Ad':'Yas']
araliq

           Ad  Yas
ID_101  Aygün   21
ID_102  Elvin   22
ID_103  Nigar   20

In [28]:
# Filter

data = {
    'Ad': ['Aygün', 'Elvin', 'Nigar', 'Samir', 'Orxan', 'Lalə'],
    'Sobesi': ['IT', 'HR', 'IT', 'Maliyyə', 'HR', 'IT'],
    'Maas': [1200, 800, 1500, 950, 750, 2000],
    'Seher': ['Bakı', 'Gəncə', 'Bakı', 'Sumqayıt', 'Bakı', 'Naxçıvan']
}

df = pd.DataFrame(data)

In [29]:
# arxa planda nə baş verir?
# Siz df['Maas'] > 1000 yazanda Pandas sizə əslində datanı vermir, o sizə True (Doğru) və False (Yanlış) siyahısı verir.

# Sadəcə şərti yoxlayaq
print(df['Maas'] > 1000)

0     True
1    False
2     True
3    False
4    False
5     True
Name: Maas, dtype: bool

In [30]:
# Biz bu True/False siyahısını DataFrame-in içinə yerləşdirəndə, Pandas yalnız True olan sətirləri bizə göstərir.

yuksek_maas = df[df['Maas'] > 1000]
print(yuksek_maas)

      Ad Sobesi  Maas     Seher
0  Aygün     IT  1200      Bakı
2  Nigar     IT  1500      Bakı
5   Lalə     IT  2000  Naxçıvan

In [32]:
# "Şöbəsi 'IT' olan və maaşı 1300-dən çox olanlar." 

# (Şərt 1) & (Şərt 2)
senior_it = df[(df['Sobesi'] == 'IT') & (df['Maas'] > 1300)]
senior_it

      Ad Sobesi  Maas     Seher
2  Nigar     IT  1500      Bakı
5   Lalə     IT  2000  Naxçıvan

In [34]:
# Ssenari: "Ya 'HR' şöbəsində işləyənlər, ya da maaşı 900-dən az olanlar."

# (Şərt 1) | (Şərt 2)
filter_or = df[(df['Sobesi'] == 'HR') | (df['Maas'] < 900)]
filter_or

      Ad Sobesi  Maas  Seher
1  Elvin     HR   800  Gəncə
4  Orxan     HR   750   Bakı

In [35]:
# (Şərt 1) & (Şərt 2)
senior_it = df[(df['Sobesi'] == 'IT') and (df['Maas'] > 1300)]
senior_it

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [36]:
filter_or = df[(df['Sobesi'] == 'HR') or (df['Maas'] < 900)]
filter_or

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [38]:
# .isin() – Siyahı üzrə yoxlama

# Ssenari: "İşçilər 'Bakı' və ya 'Gəncə' və ya 'Naxçıvan' şəhərindəndirsə gətir." 
# Uzun yol (Pis yol): df[(df['Seher'] == 'Bakı') | (df['Seher'] == 'Gəncə') | ...]

# Qısa yol (Professional yol):
seherler = ['Bakı', 'Gəncə', 'Naxçıvan']
secilenler = df[df['Seher'].isin(seherler)]
secilenler

      Ad Sobesi  Maas     Seher
0  Aygün     IT  1200      Bakı
1  Elvin     HR   800     Gəncə
2  Nigar     IT  1500      Bakı
4  Orxan     HR   750      Bakı
5   Lalə     IT  2000  Naxçıvan

In [40]:
# .between() – Aralıq yoxlama
# Ssenari: "Maaşı 800 ilə 1200 arasında olanlar."
# Uzun yol: df[(df['Maas'] >= 800) & (df['Maas'] <= 1200)]

orta_maas = df[df['Maas'].between(800, 1200)]
orta_maas

      Ad   Sobesi  Maas     Seher
0  Aygün       IT  1200      Bakı
1  Elvin       HR   800     Gəncə
3  Samir  Maliyyə   950  Sumqayıt

In [42]:
# String filter
# Ssenari: "Adının içində 'a' hərfi olan hər kəsi tap." (SQL-dəki LIKE '%a%' kimi).

# str.contains() metodu
a_herfi_olanlar = df[df['Ad'].str.contains('a', case=False)] 
# case=False: Böyük-kiçik hərf fərqini iqnor edir
a_herfi_olanlar

      Ad   Sobesi  Maas     Seher
0  Aygün       IT  1200      Bakı
2  Nigar       IT  1500      Bakı
3  Samir  Maliyyə   950  Sumqayıt
4  Orxan       HR   750      Bakı
5   Lalə       IT  2000  Naxçıvan

In [44]:
# String filter
# Ssenari: "Adının içində 'a' hərfi olan hər kəsi tap." (SQL-dəki LIKE '%a%' kimi).

# str.contains() metodu
a_herfi_olanlar = df[df['Ad'].str.contains('a', case=True)] 
# case=False: Böyük-kiçik hərf fərqini iqnor edir
a_herfi_olanlar

      Ad   Sobesi  Maas     Seher
2  Nigar       IT  1500      Bakı
3  Samir  Maliyyə   950  Sumqayıt
4  Orxan       HR   750      Bakı
5   Lalə       IT  2000  Naxçıvan

In [48]:
# Ssenari: "Adı 'E' hərfi ilə başlayanlar."

e_ile_baslayan = df[df['Ad'].str.startswith('E')]
e_ile_baslayan

      Ad Sobesi  Maas  Seher
1  Elvin     HR   800  Gəncə

In [50]:
# endswith 
# Məsələn, soyadları "ov" və ya "yeva" ilə bitənləri tapmaq üçün istifadə olunur. 

# Soyadı 'ov' ilə bitən işçiləri tapmaq
ov_ile_biten = df[df['Ad'].str.endswith('ov')]
ov_ile_biten

Empty DataFrame
Columns: [Ad, Sobesi, Maas, Seher]
Index: []

In [54]:
df = pd.DataFrame({'Seher': [' Bakı ', 'Gəncə ', ' Sumqayıt']})
print(df)

# Təmizləmədən əvvəl 'Bakı' axtarsaq tapmayacaq
# Həlli:
df['Seher'] = df['Seher'].str.strip()
df

       Seher
0      Bakı
1     Gəncə
2   Sumqayıt

      Seher
0      Bakı
1     Gəncə
2  Sumqayıt

In [55]:
# .query() Metodu: Datanı "Danışaraq" Filtrləmək

data = {
    'Ad': ['Aygün', 'Elvin', 'Nigar', 'Samir', 'Orxan'],
    'Bolge': ['Bakı', 'Gəncə', 'Bakı', 'Sumqayıt', 'Gəncə'],
    'Satis': [1200, 800, 1500, 400, 2000],
    'Mehsul': ['Telefon', 'TV', 'Telefon', 'Notbuk', 'TV']
}

df = pd.DataFrame(data)

In [57]:
# Diqqət: Bütün sorğu dırnaq ' ' içində yazılır
netice = df.query('Satis > 1000')
netice

      Ad  Bolge  Satis   Mehsul
0  Aygün   Bakı   1200  Telefon
2  Nigar   Bakı   1500  Telefon
4  Orxan  Gəncə   2000       TV

In [59]:
# 'Bolge' sütunu "Bakı"-ya bərabər olsun AND 'Mehsul' sütunu "Telefon"-a
bakida_telefon = df.query('Bolge == "Bakı" and Mehsul == "Telefon"')
bakida_telefon

      Ad Bolge  Satis   Mehsul
0  Aygün  Bakı   1200  Telefon
2  Nigar  Bakı   1500  Telefon

In [61]:
gence_veya_ucuz = df.query('Bolge == "Gəncə" or Satis < 500')
gence_veya_ucuz

      Ad     Bolge  Satis  Mehsul
1  Elvin     Gəncə    800      TV
3  Samir  Sumqayıt    400  Notbuk
4  Orxan     Gəncə   2000      TV

In [63]:
# Məntiq: (Şərt 1 və Şərt 2) VƏ YA (Şərt 3)
qarisiq = df.query('(Bolge == "Bakı" and Mehsul == "TV") or Satis > 1800')
qarisiq

      Ad  Bolge  Satis Mehsul
4  Orxan  Gəncə   2000     TV

In [68]:
# fayl oxumaq 
# excel

# 1. Faylın tam yolunu dəyişənə mənimsədirik
# Diqqət: Dırnaqdan əvvəl 'r' hərfi yazırıq!
fayl_yolu = pd.read_excel(r'C:\Users\ACER\Desktop\Pandas.xlsx')
fayl_yolu

     İl  Faiz
0  2018  13.6
1  2019  25.5
2  2021  43.6
3  2022 -19.8
4  2023 -13.8
5  2024  12.0
6  2025  36.3

In [75]:
# 1. Ünvanı dəyişənə qoyuruq (Sizin yazdığınız hissə)
fayl_yolu = r'C:\Users\ACER\Desktop\Pandas.xlsx'

# 2. ƏSAS HİSSƏ: Pandas gedib o ünvandan faylı oxuyur
# 'X' vərəqini oxuyub 'df' adlı dəyişənə qoyuruq
df = pd.read_excel(fayl_yolu, sheet_name='Y')

# 3. Nəticəni ekrana veririk ki, gəlib-gəlmədiyini görək
print(df)

     İl  Faiz
0  2018  13.6
1  2019  25.5
2  2020  43.6
3  2021 -19.8
4  2022 -13.8
5  2023  12.0
6  2024  36.3

In [74]:
# 1. Ünvanı dəyişənə qoyuruq (Sizin yazdığınız hissə)
fayl_yolu = r'C:\Users\ACER\Desktop\Pandas.xlsx'

# 2. ƏSAS HİSSƏ: Pandas gedib o ünvandan faylı oxuyur
# 'X' vərəqini oxuyub 'df' adlı dəyişənə qoyuruq
df2 = pd.read_excel(fayl_yolu, sheet_name='X')

# 3. Nəticəni ekrana veririk ki, gəlib-gəlmədiyini görək
print(df2)

     İl  Faiz
0  2018   6.5
1  2019   4.4
2  2020   3.8
3  2021   6.9
4  2022   8.0
5  2023   5.8
6  2024   5.1

In [80]:


print("\n--- Sheet Y and X (df2) Statistikası ---")
# describe() bizə ədədi ortanı, min və max dəyərləri verir
print(df.describe())
print(df2.describe())

--- Sheet Y and X (df2) Statistikası ---
                İl       Faiz
count     7.000000   7.000000
mean   2021.000000  13.914286
std       2.160247  23.892428
min    2018.000000 -19.800000
25%    2019.500000  -0.900000
50%    2021.000000  13.600000
75%    2022.500000  30.900000
max    2024.000000  43.600000
                İl      Faiz
count     7.000000  7.000000
mean   2021.000000  5.785714
std       2.160247  1.471313
min    2018.000000  3.800000
25%    2019.500000  4.750000
50%    2021.000000  5.800000
75%    2022.500000  6.700000
max    2024.000000  8.000000

In [81]:
print("\n--- Sheet Y and X (df2) Statistikası ---")
# describe() bizə ədədi ortanı, min və max dəyərləri verir
print(df['Faiz'].describe())
print(df2['Faiz'].describe())

--- Sheet Y and X (df2) Statistikası ---
count     7.000000
mean     13.914286
std      23.892428
min     -19.800000
25%      -0.900000
50%      13.600000
75%      30.900000
max      43.600000
Name: Faiz, dtype: float64
count    7.000000
mean     5.785714
std      1.471313
min      3.800000
25%      4.750000
50%      5.800000
75%      6.700000
max      8.000000
Name: Faiz, dtype: float64

In [82]:
# df (Y vərəqi) üçün ad dəyişimi
df = df.rename(columns={'Faiz': 'Faiz_Y'})

# df2 (X vərəqi) üçün ad dəyişimi
df2 = df2.rename(columns={'Faiz': 'Faiz_X'})

# Yoxlayaq
print(df.head(2))
print(df2.head(2))

     İl  Faiz_Y
0  2018    13.6
1  2019    25.5
     İl  Faiz_X
0  2018     6.5
1  2019     4.4

In [86]:
# cedvelleri birleşdirme

# 1-ci Hissə: Əgər df və df2 (Sizin Exceldən oxuduqlarınız) hazırdırsa, əvvəlcə onları birləşdirək
# Bu sətir df_main-i yaradır:
df_main = pd.merge(df, df2, on='İl', how='inner')
df_main

     İl  Faiz_Y  Faiz_X
0  2018    13.6     6.5
1  2019    25.5     4.4
2  2020    43.6     3.8
3  2021   -19.8     6.9
4  2022   -13.8     8.0
5  2023    12.0     5.8
6  2024    36.3     5.1

In [88]:
# Dörd Əsas Əməliyyat

# 1. Toplama (Cəm göstərici)
df_main['Cem_Faiz'] = df_main['Faiz_X'] + df_main['Faiz_Y']

# 2. Çıxma (Fərq)
df_main['Ferq'] = df_main['Faiz_X'] - df_main['Faiz_Y']

# 3. Vurma (Məsələn, faizi əmsala vurmaq)
df_main['Faiz_X_2qat'] = df_main['Faiz_X'] * 2

# 4. Mürəkkəb Hesablama (Ortalama)
# Mötərizədən istifadə etmək mütləqdir!
df_main['Ortalama'] = (df_main['Faiz_X'] + df_main['Faiz_Y']) / 2

print(df_main)

     İl  Faiz_Y  Faiz_X  Cem_Faiz  Ferq  Faiz_X_2qat  Ortalama
0  2018    13.6     6.5      20.1  -7.1         13.0     10.05
1  2019    25.5     4.4      29.9 -21.1          8.8     14.95
2  2020    43.6     3.8      47.4 -39.8          7.6     23.70
3  2021   -19.8     6.9     -12.9  26.7         13.8     -6.45
4  2022   -13.8     8.0      -5.8  21.8         16.0     -2.90
5  2023    12.0     5.8      17.8  -6.2         11.6      8.90
6  2024    36.3     5.1      41.4 -31.2         10.2     20.70

In [92]:
# Statistik Əməliyyatlar (Sütun daxili)
# Bəzən bir sütunu digəri ilə yox, öz daxilində hesablamaq lazımdır.

# Bütün Faiz_X sütununu cəmləmək
total_x = df_main['Faiz_X'].sum()
print(total_x)

# Kümülatif Cəm (İllər üzrə yığılaraq gedən artım)
df2['Kumulyativ_X'] = df_main['Faiz_X'].cumsum()
print(df2)

40.5
     İl  Faiz_X  Kumulyativ_X
0  2018     6.5           6.5
1  2019     4.4          10.9
2  2020     3.8          14.7
3  2021     6.9          21.6
4  2022     8.0          29.6
5  2023     5.8          35.4
6  2024     5.1          40.5

In [94]:
# pivot 

import pandas as pd
import numpy as np

data = {
    'Seher': ['Bakı', 'Bakı', 'Bakı', 'Gəncə', 'Gəncə', 'Sumqayıt', 'Sumqayıt'],
    'Mehsul': ['Telefon', 'TV', 'Telefon', 'TV', 'Telefon', 'Telefon', 'TV'],
    'Satis': [1000, 2000, 1200, 1500, 800, 900, 1800],
    'Miqdar': [2, 1, 3, 2, 4, 2, 1]
}

df = pd.DataFrame(data)
print("--- İlkin Data ---")
print(df)

--- İlkin Data ---
      Seher   Mehsul  Satis  Miqdar
0      Bakı  Telefon   1000       2
1      Bakı       TV   2000       1
2      Bakı  Telefon   1200       3
3     Gəncə       TV   1500       2
4     Gəncə  Telefon    800       4
5  Sumqayıt  Telefon    900       2
6  Sumqayıt       TV   1800       1

In [95]:
pivot1 = df.pivot_table(index='Seher', values='Satis', aggfunc='sum')
print(pivot1)

          Satis
Seher
Bakı       4200
Gəncə      2300
Sumqayıt   2700

In [96]:
pivot2 = df.pivot_table(index='Seher',      # Sətirlərdə Şəhər olsun
                        columns='Mehsul',   # Sütunlarda Məhsul olsun
                        values='Satis',     # Hesablanan Satış olsun
                        aggfunc='sum')      # Cəmləsin

print(pivot2)

Mehsul      TV  Telefon
Seher
Bakı      2000     2200
Gəncə     1500      800
Sumqayıt  1800      900

In [98]:
# Boşluqları Doldurmaq (fill_value)

# Məsələn, Gəncədə TV satışı yoxdursa, 0 yazsın
pivot2 = df.pivot_table(index='Seher', columns='Mehsul', values='Satis', aggfunc='sum', fill_value=0)
pivot2

Mehsul      TV  Telefon
Seher
Bakı      2000     2200
Gəncə     1500      800
Sumqayıt  1800      900

In [99]:
# Cəmi Göstərmək (margins)
# Excel-dəki "Grand Total" (Yekun Cəm) sətrini əlavə etmək üçün.

pivot_total = df.pivot_table(index='Seher', 
                             columns='Mehsul', 
                             values='Satis', 
                             aggfunc='sum',
                             margins=True,       # Yekun cəmi aktiv et
                             margins_name='CƏM') # Adını qoy

print(pivot_total)

Mehsul      TV  Telefon   CƏM
Seher
Bakı      2000     2200  4200
Gəncə     1500      800  2300
Sumqayıt  1800      900  2700
CƏM       5300     3900  9200

In [100]:
# Çoxlu Funksiya Tətbiqi
# Analitik eyni anda həm Satışın Cəmini, həm də Satılan Miqdarın Ortalamasını görmək istəyə bilər.

pivot_multi = df.pivot_table(index='Seher',
                             values=['Satis', 'Miqdar'], # İki fərqli sütun
                             aggfunc={'Satis': 'sum', 'Miqdar': 'mean'}) # Hərəsinə ayrı funksiya

print(pivot_multi)

          Miqdar  Satis
Seher
Bakı         2.0   4200
Gəncə        3.0   2300
Sumqayıt     1.5   2700

In [102]:
pivot_istenilen = pivot_multi[['Satis', 'Miqdar']]
pivot_istenilen

          Satis  Miqdar
Seher
Bakı       4200     2.0
Gəncə      2300     3.0
Sumqayıt   2700     1.5