In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\ACER\Desktop\student_data.xlsx")
df

,Sifaris_ID,Tarix,Musteri,Bolge,Kateqoriya,Mehsul,Miqdar,Vahid_Qiymet,Endirim_%,Satici
0,SIF-1001,2024-05-10,Musteri_3,NaN,Elektronika,Laptop,NaN,339.97,20.0,Murad A.
1,SIF-1002,2024-02-20,Musteri_23,Baki,Idman,Ip,NaN,18.14,5.0,Anar M.
2,SIF-1003,2024-11-15,Musteri_11,Ganja,Idman,Ip,NaN,84.03,15.0,Sevinc Q.
3,SIF-1004,2024-03-07,Musteri_9,Ganja,Erzaq,Yag,6.0,424.51,20.0,Murad A.
4,SIF-1005,2024-08-05,Musteri_19,Shaki,Elektronika,Qulaqliq,6.0,311.17,10.0,Anar M.
...,...,...,...,...,...,...,...,...,...,...
75,SIF-1076,2024-10-30,Musteri_18,Sumqayit,Erzaq,Yag,9.0,NaN,0.0,Anar M.
76,SIF-1077,2024-03-07,Musteri_2,NaN,Erzaq,Yag,1.0,223.03,5.0,Sevinc Q.
77,SIF-1078,2024-08-05,Musteri_5,Baki,Erzaq,Cay,NaN,344.79,5.0,Anar M.
78,SIF-1079,2024-03-07,Musteri_25,Baki,Idman,Xantell,36.0,396.42,5.0,Leyla H.
79,SIF-1080,2024-06-14,Musteri_24,Lankaran,Idman,Ip,38.0,312.41,20.0,Sevinc Q.

In [3]:
# 1. Bolge sütunundakı null dəyərləri ən çox təkrarlanan (mode) dəyərlə dolduraq
# mode() funksiyası siyahı qaytardığı üçün [0] indeksini götürürük
most_frequent_bolge = df['Bolge'].mode()[0]
df['Bolge'] = df['Bolge'].fillna(most_frequent_bolge)

# 2. Miqdar sütunundakı null dəyərləri ədədi orta (mean) ilə dolduraq
average_miqdar = df['Miqdar'].mean()
df['Miqdar'] = df['Miqdar'].fillna(average_miqdar)

# 3. Endirim_% sütunundakı null dəyərləri 0 ilə dolduraq
df['Endirim_%'] = df['Endirim_%'].fillna(0)

# Nəticəni yoxlayaq
print(df.isnull().sum()) # Null dəyərlərin qalıb-qalmadığını görmək üçün

Sifaris_ID      0
Tarix           0
Musteri         0
Bolge           0
Kateqoriya      0
Mehsul          0
Miqdar          0
Vahid_Qiymet    4
Endirim_%       0
Satici          0
dtype: int64

In [5]:
# Vahid_Qiymet sütunundakı null dəyərləri median ilə dolduraq
median_qiymet = df['Vahid_Qiymet'].median()
df['Vahid_Qiymet'] = df['Vahid_Qiymet'].fillna(median_qiymet)

# Nəticəni yoxlayaq
print(df.isnull().sum()) # Null dəyərlərin qalıb-qalmadığını görmək üçün

Sifaris_ID      0
Tarix           0
Musteri         0
Bolge           0
Kateqoriya      0
Mehsul          0
Miqdar          0
Vahid_Qiymet    0
Endirim_%       0
Satici          0
dtype: int64

In [10]:
# 1. Sadəcə Hasil (Endirimsiz Məbləğ)
df['Umumi_Mebleg'] = df['Miqdar'] * df['Vahid_Qiymet']

# 2. Endirimi nəzərə alan Net Gəlir (Əsl qazanc)
df['Net_Gelir'] = df['Miqdar'] * df['Vahid_Qiymet'] * (1 - df['Endirim_%'] / 100)

# Nəticənin ilk 5 sətrinə baxaq
print(df.head(5))

  Sifaris_ID       Tarix     Musteri  Bolge   Kateqoriya    Mehsul     Miqdar  \
0   SIF-1001  2024-05-10   Musteri_3   Baki  Elektronika    Laptop  24.282609
1   SIF-1002  2024-02-20  Musteri_23   Baki        Idman        Ip  24.282609
2   SIF-1003  2024-11-15  Musteri_11  Ganja        Idman        Ip  24.282609
3   SIF-1004  2024-03-07   Musteri_9  Ganja        Erzaq       Yag   6.000000
4   SIF-1005  2024-08-05  Musteri_19  Shaki  Elektronika  Qulaqliq   6.000000

   Vahid_Qiymet  Endirim_%     Satici  Umumi_Mebleg    Net_Gelir
0        339.97       20.0   Murad A.   8255.358478  6604.286783
1         18.14        5.0    Anar M.    440.486522   418.462196
2         84.03       15.0  Sevinc Q.   2040.467609  1734.397467
3        424.51       20.0   Murad A.   2547.060000  2037.648000
4        311.17       10.0    Anar M.   1867.020000  1680.318000

In [11]:
# NET GELIR HISSESINI 2 EDED QALMAQ SERTI ILE YUVARLAQLASDIRAQ
df['Net_Gelir'] = df['Net_Gelir'].round(2)
df.head(5)

,Sifaris_ID,Tarix,Musteri,Bolge,Kateqoriya,Mehsul,Miqdar,Vahid_Qiymet,Endirim_%,Satici,Umumi_Mebleg,Net_Gelir
0,SIF-1001,2024-05-10,Musteri_3,Baki,Elektronika,Laptop,24.282609,339.97,20.0,Murad A.,8255.358478,6604.29
1,SIF-1002,2024-02-20,Musteri_23,Baki,Idman,Ip,24.282609,18.14,5.0,Anar M.,440.486522,418.46
2,SIF-1003,2024-11-15,Musteri_11,Ganja,Idman,Ip,24.282609,84.03,15.0,Sevinc Q.,2040.467609,1734.40
3,SIF-1004,2024-03-07,Musteri_9,Ganja,Erzaq,Yag,6.000000,424.51,20.0,Murad A.,2547.060000,2037.65
4,SIF-1005,2024-08-05,Musteri_19,Shaki,Elektronika,Qulaqliq,6.000000,311.17,10.0,Anar M.,1867.020000,1680.32

In [12]:
# 1. Bölgə üzrə Net Gəlir
bolge_pivot = df.pivot_table(index='Bolge', values='Net_Gelir', aggfunc='sum')

# 2. Kateqoriya üzrə Net Gəlir
kateqoriya_pivot = df.pivot_table(index='Kateqoriya', values='Net_Gelir', aggfunc='sum')

# 3. Məhsul üzrə Net Gəlir
mehsul_pivot = df.pivot_table(index='Mehsul', values='Net_Gelir', aggfunc='sum')

# Nəticələri ekrana çıxaraq
print("--- Bölgə üzrə Gəlir ---")
print(bolge_pivot)
print("\n--- Kateqoriya üzrə Gəlir ---")
print(kateqoriya_pivot)
print("\n--- Məhsul üzrə Gəlir ---")
print(mehsul_pivot)

--- Bölgə üzrə Gəlir ---
          Net_Gelir
Bolge
Baki      240743.49
Ganja      77178.06
Lankaran   63260.88
Shaki      47811.77
Sumqayit   76090.46

--- Kateqoriya üzrə Gəlir ---
             Net_Gelir
Kateqoriya
Elektronika   52602.50
Erzaq         66578.33
Ev esyalari   45378.87
Geyim        169140.19
Idman        171384.77

--- Məhsul üzrə Gəlir ---
           Net_Gelir
Mehsul
Cay         11245.38
Divan       19524.09
Ip          60517.87
Kofye       28894.44
Kostyum     30776.79
Koynk       77838.09
Krossovka   31324.50
Laptop      12417.79
Masa         7235.97
Matras      16146.41
Monitor      5099.88
Palto       29200.81
Planset      7562.00
Qulaqliq    22758.00
Seker        5859.66
Shkaf        4373.27
Stul        12405.83
Telefon      4764.83
Topu        29762.60
Un           5601.92
Velosiped   26727.05
Xali         1839.71
Xantell     38230.84
Yag         14976.93

In [15]:
# Kateqoriya sətirlərdə, Məhsullar sütunlarda olmaqla net gəlir cəmi
kat_mehsul_pivot = df.pivot_table(index='Kateqoriya', 
                                  columns='Bolge', 
                                  values='Net_Gelir', 
                                  aggfunc='sum')



# Nəticəni göstərək
print(kat_mehsul_pivot)

Bolge            Baki     Ganja  Lankaran     Shaki  Sumqayit
Kateqoriya
Elektronika  26608.53  21077.68       NaN   4498.83    417.46
Erzaq        35719.89  12020.15    792.72   3929.33  14116.24
Ev esyalari  10071.05   2768.11  15637.65   7210.08   9691.98
Geyim        85465.88  24185.17  14045.70   5948.85  39494.59
Idman        82878.14  17126.95  32784.81  26224.68  12370.19

In [17]:
# Null (NaN) dəyərləri 0 ilə əvəzləyək ki, daha təmiz görünsün
# (Çünki bir kateqoriyaya aid olmayan məhsul orada NaN görsənəcək)
kat_mehsul_pivot = kat_mehsul_pivot.fillna(0)
kat_mehsul_pivot

Bolge            Baki     Ganja  Lankaran     Shaki  Sumqayit
Kateqoriya
Elektronika  26608.53  21077.68      0.00   4498.83    417.46
Erzaq        35719.89  12020.15    792.72   3929.33  14116.24
Ev esyalari  10071.05   2768.11  15637.65   7210.08   9691.98
Geyim        85465.88  24185.17  14045.70   5948.85  39494.59
Idman        82878.14  17126.95  32784.81  26224.68  12370.19

In [20]:
df_musteriler = pd.read_excel(r"C:\Users\ACER\Desktop\student_data.xlsx",sheet_name="Musteriler")
df_musteriler.head(5)

  Musteri_ID     Musteri   Yas     Sehir              Email Uzvluk_Novbesi
0  Musteri_1  Ad_Soyad_1   NaN  Sumqayit  musteri1@mail.com         Bronze
1  Musteri_2  Ad_Soyad_2  29.0  Lankaran  musteri2@mail.com       Platinum
2  Musteri_3  Ad_Soyad_3  48.0  Sumqayit  musteri3@mail.com       Platinum
3  Musteri_4  Ad_Soyad_4   NaN     Shaki  musteri4@mail.com         Silver
4  Musteri_5  Ad_Soyad_5  52.0  Sumqayit  musteri5@mail.com         Silver

In [28]:
# 2. Bunu müştəri məlumatları (status) ilə birləşdirək
son_hesabat = pd.merge(musteri_gelir, 
                       df_musteriler[['Musteri_ID', 'Uzvluk_Novbesi']], # Musteri_ID bura daxil edilməlidir
                       left_on='Musteri', 
                       right_on='Musteri_ID', 
                       how='left')

# Əgər hər iki sütun (Musteri və Musteri_ID) cədvəldə qalsa, birini silə bilərsiniz:
son_hesabat

       Musteri  Net_Gelir  Musteri_ID Uzvluk_Novbesi
0    Musteri_1   24710.36   Musteri_1         Bronze
1   Musteri_10   24186.77  Musteri_10       Platinum
2   Musteri_11   12347.57  Musteri_11       Platinum
3   Musteri_12   11451.74  Musteri_12           Gold
4   Musteri_13   36200.31  Musteri_13           Gold
5   Musteri_14   25128.14  Musteri_14         Bronze
6   Musteri_15   48018.66  Musteri_15         Bronze
7   Musteri_17   35281.15  Musteri_17           Gold
8   Musteri_18   28282.41  Musteri_18         Bronze
9   Musteri_19   14665.35  Musteri_19         Bronze
10   Musteri_2    1834.86   Musteri_2       Platinum
11  Musteri_20    7210.08  Musteri_20       Platinum
12  Musteri_21    3499.46  Musteri_21           Gold
13  Musteri_22    6068.87  Musteri_22         Silver
14  Musteri_23    7795.28  Musteri_23           Gold
15  Musteri_24    9497.26  Musteri_24         Bronze
16  Musteri_25   22700.06  Musteri_25         Silver
17  Musteri_26    5643.40  Musteri_26       Platinum
18  Musteri_27   26781.31  Musteri_27       Platinum
19  Musteri_29   18416.23  Musteri_29         Silver
20   Musteri_3   13158.12   Musteri_3       Platinum
21  Musteri_30    3189.97  Musteri_30         Bronze
22   Musteri_4    1880.79   Musteri_4         Silver
23   Musteri_5   28720.49   Musteri_5         Silver
24   Musteri_6    9050.86   Musteri_6           Gold
25   Musteri_7    4943.45   Musteri_7       Platinum
26   Musteri_8   51513.71   Musteri_8           Gold
27   Musteri_9   22908.00   Musteri_9         Bronze

In [29]:
# Əgər hər iki sütun (Musteri və Musteri_ID) cədvəldə qalsa, birini silə bilərsiniz:
son_hesabat = son_hesabat.drop('Musteri_ID', axis=1)

son_hesabat

       Musteri  Net_Gelir Uzvluk_Novbesi
0    Musteri_1   24710.36         Bronze
1   Musteri_10   24186.77       Platinum
2   Musteri_11   12347.57       Platinum
3   Musteri_12   11451.74           Gold
4   Musteri_13   36200.31           Gold
5   Musteri_14   25128.14         Bronze
6   Musteri_15   48018.66         Bronze
7   Musteri_17   35281.15           Gold
8   Musteri_18   28282.41         Bronze
9   Musteri_19   14665.35         Bronze
10   Musteri_2    1834.86       Platinum
11  Musteri_20    7210.08       Platinum
12  Musteri_21    3499.46           Gold
13  Musteri_22    6068.87         Silver
14  Musteri_23    7795.28           Gold
15  Musteri_24    9497.26         Bronze
16  Musteri_25   22700.06         Silver
17  Musteri_26    5643.40       Platinum
18  Musteri_27   26781.31       Platinum
19  Musteri_29   18416.23         Silver
20   Musteri_3   13158.12       Platinum
21  Musteri_30    3189.97         Bronze
22   Musteri_4    1880.79         Silver
23   Musteri_5   28720.49         Silver
24   Musteri_6    9050.86           Gold
25   Musteri_7    4943.45       Platinum
26   Musteri_8   51513.71           Gold
27   Musteri_9   22908.00         Bronze

In [34]:
# 2. Bunu müştəri məlumatları (status) ilə birləşdirək
son_hesabat = pd.merge(df_musteriler[['Musteri_ID', 'Uzvluk_Novbesi']], 
                       musteri_gelir, # Musteri_ID bura daxil edilməlidir
                       left_on='Musteri_ID', 
                       right_on='Musteri', 
                       how='left')

# Əgər hər iki sütun (Musteri və Musteri_ID) cədvəldə qalsa, birini silə bilərsiniz:
son_hesabat = son_hesabat.drop('Musteri', axis=1)

son_hesabat

    Musteri_ID Uzvluk_Novbesi  Net_Gelir
0    Musteri_1         Bronze   24710.36
1    Musteri_2       Platinum    1834.86
2    Musteri_3       Platinum   13158.12
3    Musteri_4         Silver    1880.79
4    Musteri_5         Silver   28720.49
5    Musteri_6           Gold    9050.86
6    Musteri_7       Platinum    4943.45
7    Musteri_8           Gold   51513.71
8    Musteri_9         Bronze   22908.00
9   Musteri_10       Platinum   24186.77
10  Musteri_11       Platinum   12347.57
11  Musteri_12           Gold   11451.74
12  Musteri_13           Gold   36200.31
13  Musteri_14         Bronze   25128.14
14  Musteri_15         Bronze   48018.66
15  Musteri_16           Gold        NaN
16  Musteri_17           Gold   35281.15
17  Musteri_18         Bronze   28282.41
18  Musteri_19         Bronze   14665.35
19  Musteri_20       Platinum    7210.08
20  Musteri_21           Gold    3499.46
21  Musteri_22         Silver    6068.87
22  Musteri_23           Gold    7795.28
23  Musteri_24         Bronze    9497.26
24  Musteri_25         Silver   22700.06
25  Musteri_26       Platinum    5643.40
26  Musteri_27       Platinum   26781.31
27  Musteri_28       Platinum        NaN
28  Musteri_29         Silver   18416.23
29  Musteri_30         Bronze    3189.97

In [35]:
# Net_Gelir sütunu boş (NaN) olan sətirləri tapaq
geliri_olmayanlar = son_hesabat[son_hesabat['Net_Gelir'].isnull()]

# Nəticəni göstərək
print(geliri_olmayanlar)

    Musteri_ID Uzvluk_Novbesi  Net_Gelir
15  Musteri_16           Gold        NaN
27  Musteri_28       Platinum        NaN